# Generated by Django 4.2.1 on 2023-05-31 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, verbose_name='Placa')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=20, verbose_name='Modelo')),
                ('cor', models.CharField(max_length=20, verbose_name='Cor')),
            ],
            options={
                'verbose_name_plural': 'Carros',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=100, verbose_name='Rua')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('numero', models.IntegerField(default=0, verbose_name='Número')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('cep', models.IntegerField(default=0, verbose_name='CEP')),
            ],
            options={
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do evento')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('criticidade', models.CharField(max_length=50, verbose_name='Criticidade')),
            ],
            options={
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('identificacao', models.IntegerField(default=0, verbose_name='Identificação')),
                ('telefone', models.IntegerField(default=0, verbose_name='Identificação')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.endereco', verbose_name='Endereço')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicio', models.DateTimeField(verbose_name='Data de início')),
                ('dataFim', models.DateTimeField(verbose_name='Data de fim')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('tempoReserva', models.TimeField(verbose_name='Tempo de reserva')),
            ],
            options={
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.pessoa')),
                ('matricula', models.IntegerField(default=0, verbose_name='Matrícula')),
                ('cargo', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name_plural': 'Administradores',
            },
            bases=('core.pessoa',),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.pessoa')),
                ('dataNascimento', models.DateField(verbose_name='Data de Nascimento')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
            bases=('core.pessoa',),
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.pessoa')),
                ('registro', models.IntegerField(default=0, verbose_name='Registro')),
                ('especialidade', models.CharField(max_length=50, verbose_name='Especialidade')),
            ],
            options={
                'verbose_name_plural': 'Prestadores',
            },
            bases=('core.pessoa',),
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupado', models.BooleanField(verbose_name='Ocupado?')),
                ('recarga', models.BooleanField(verbose_name='Possui recarga?')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.endereco', verbose_name='Endereço')),
            ],
            options={
                'verbose_name_plural': 'Vagas',
            },
        ),
        migrations.CreateModel(
            name='PontoDeApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('terceirizado', models.BooleanField(verbose_name='Terceirizado?')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.endereco', verbose_name='Endereço')),
            ],
            options={
                'verbose_name_plural': 'Pontos de Apoio',
            },
        ),
        migrations.CreateModel(
            name='EventoCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicio', models.DateTimeField(verbose_name='Data de início')),
                ('dataFim', models.DateTimeField(verbose_name='Data de fim')),
                ('resolvido', models.BooleanField(verbose_name='Resolvido?')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.carro', verbose_name='Carro')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.evento', verbose_name='Evento')),
            ],
        ),
        migrations.AddField(
            model_name='carro',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.vaga', verbose_name='Vaga'),
        ),
    ]
