# Generated by Django 4.2.1 on 2023-06-03 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='eventocarro',
            name='carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.carro', verbose_name='Carro'),
        ),
        migrations.AddField(
            model_name='eventocarro',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.evento', verbose_name='Evento'),
        ),
        migrations.AddField(
            model_name='carro',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.vaga', verbose_name='Vaga'),
        ),
    ]
