# Generated by Django 4.2.1 on 2023-06-09 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_administrador_isactive_carro_isactive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='eventocarro',
            name='isActive',
        ),
        migrations.AddField(
            model_name='reserva',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaga',
            name='carga',
            field=models.BooleanField(default=True, verbose_name='Carregamento?'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuarioPadrao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
