# Generated by Django 4.2.1 on 2023-06-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_evento_isactive_remove_eventocarro_isactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocarro',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
    ]
