# Generated by Django 4.2.1 on 2023-06-09 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_eventocarro_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='email',
        ),
    ]
