# Generated by Django 4.2.1 on 2023-06-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_pessoa_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='carga',
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.IntegerField(default=0, verbose_name='Telefone'),
        ),
    ]
