# Generated by Django 4.2.1 on 2023-06-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_vaga_carga_alter_pessoa_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='placa',
            field=models.CharField(max_length=8, verbose_name='Placa'),
        ),
    ]
