# Generated by Django 4.2.1 on 2023-06-10 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_carro_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='vaga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.vaga', verbose_name='Vaga'),
        ),
    ]
