# Generated by Django 4.2.1 on 2023-06-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_carro_vaga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='placa',
            field=models.CharField(max_length=20, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='ocupado',
            field=models.BooleanField(default=False, verbose_name='Ocupado?'),
        ),
    ]
