# Generated by Django 4.2.1 on 2023-06-10 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_carro_placa_alter_vaga_ocupado'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='Nome',
            field=models.CharField(default='Vaga', max_length=20, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='vaga',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.vaga', verbose_name='Vaga'),
        ),
    ]
