# Generated by Django 4.2.1 on 2023-06-10 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_vaga_nome_alter_carro_vaga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaga',
            old_name='Nome',
            new_name='nome',
        ),
    ]
