# Generated by Django 4.2.1 on 2023-06-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_nome_vaga_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='disponível',
            field=models.BooleanField(default=True, verbose_name='Disponível?'),
        ),
    ]
