# Generated by Django 4.2.1 on 2023-06-10 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_carro_disponível_carro_disponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='carro',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.carro', verbose_name='Carro'),
        ),
    ]
