# Generated by Django 4.2.1 on 2023-06-10 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_reserva_carro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='user',
        ),
        migrations.AddField(
            model_name='reserva',
            name='pessoa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='core.pessoa', verbose_name='User'),
            preserve_default=False,
        ),
    ]
