# Generated by Django 4.2.1 on 2023-06-10 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_reserva_user_reserva_pessoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='core.cliente', verbose_name='Cliente'),
            preserve_default=False,
        ),
    ]
