# Generated by Django 4.2.1 on 2023-06-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_reserva_temporeserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
    ]
