# Generated by Django 4.2.1 on 2023-06-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_evento_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventocarro',
            name='dataFim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de fim'),
        ),
        migrations.AlterField(
            model_name='eventocarro',
            name='resolvido',
            field=models.BooleanField(default=False, verbose_name='Resolvido?'),
        ),
    ]
