# Generated by Django 4.2.1 on 2023-06-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_eventocarro_datafim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventocarro',
            name='dataFim',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Data de fim'),
        ),
    ]
