# Generated by Django 4.2.1 on 2023-06-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_eventocarro_datafim'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='cargo',
            field=models.CharField(max_length=100, verbose_name='Cargo'),
        ),
    ]
